# Generated by Django 3.2 on 2021-09-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('photo', models.CharField(max_length=200, null=True)),
                ('template', models.IntegerField(null=True)),
                ('color', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('address', models.TextField(null=True)),
                ('telp', models.IntegerField(null=True)),
                ('social', models.TextField(null=True)),
                ('education', models.TextField(null=True)),
                ('vision', models.TextField(null=True)),
                ('skill', models.TextField(null=True)),
                ('achievement', models.TextField(null=True)),
                ('experience', models.TextField(null=True)),
            ],
        ),
    ]
