# Generated by Django 4.2.6 on 2024-05-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='telp',
            field=models.TextField(null=True),
        ),
    ]
