# Generated by Django 4.2.6 on 2024-08-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abdi', '0002_alter_data_telp'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='ttl',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
