# Generated by Django 4.2.6 on 2024-08-09 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abdi', '0003_data_ttl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='ttl',
        ),
    ]
