# Generated by Django 4.2.6 on 2024-09-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abdi', '0005_rename_description_data_career_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='career',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='profile',
            new_name='vision',
        ),
    ]
