# Generated by Django 4.2.6 on 2024-09-13 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abdi', '0006_rename_career_data_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='description',
            new_name='career',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='vision',
            new_name='profile',
        ),
    ]
