# Generated by Django 4.2.6 on 2024-09-13 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abdi', '0007_rename_description_data_career_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='profile',
            new_name='summary',
        ),
    ]
